name: Build Go module
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      goVersion:
        type: choice
        description: go Versions
        requires: true
        options: 
        - 1.18
        - 1.19
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check go version 
      run: |
        echo "Go version is" ${{ github.event.inputs.goVersion }}
    - name: Set up Go env
      uses: actions/setup-go@v3
      with:
        go-version: github.event.inputs.goVersion

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies & build
      working-directory: .
      run: go build -mod=readonly -v

    - name: Test
      working-directory: .
      run: echo "There are not existing tests yet"